osx_image: xcode9
language: objective-c

script: 
    - xcodebuild -workspace LetterAvatarKit.xcodeproj -sdk iphonesimulator -scheme LetterAvatarKit -destination 'platform=iOS Simulator,name=iPhone 6s,OS=11.0' test | xcpretty --test --color
